require 'thor'
require 'fileutils'
require 'tempfile'
require 'yaml'
require 'aws-sdk'

require_relative 'hygroscope/cli'
require_relative 'hygroscope/stack'
require_relative 'hygroscope/template'
require_relative 'hygroscope/paramset'
require_relative 'hygroscope/payload'
